#!/bin/bash

# Pulse Engagement Tracker Deployment Script
# Usage: ./deploy.sh [dev|prod]

set -e

ENV=${1:-dev}
REGION="us-east-1"
STACK_NAME="pulse-engagement-tracker"
DOMAIN="pulse.elelem.expert"

if [ "$ENV" == "prod" ]; then
    STACK_NAME="pulse-engagement-tracker-prod"
fi

echo "============================================"
echo "Deploying Pulse Engagement Tracker ($ENV)"
echo "============================================"

# Check if logged into AWS
echo "Checking AWS credentials..."
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo "Not logged into AWS. Running saml2aws login..."
    saml2aws login -a prod-aicoe-admin --skip-prompt
fi

echo "AWS Account: $(aws sts get-caller-identity --query Account --output text)"

# Build SAM application
echo ""
echo "Building SAM application..."
sam build

# Deploy SAM stack
echo ""
echo "Deploying SAM stack..."
if [ "$ENV" == "prod" ]; then
    sam deploy --config-env prod
else
    sam deploy
fi

# Get outputs
echo ""
echo "Retrieving stack outputs..."
API_URL=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
    --output text \
    --region $REGION)

WEBSITE_BUCKET=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucket'].OutputValue" \
    --output text \
    --region $REGION)

WEBSITE_URL=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query "Stacks[0].Outputs[?OutputKey=='WebsiteUrl'].OutputValue" \
    --output text \
    --region $REGION)

echo "API URL: $API_URL"
echo "Website Bucket: $WEBSITE_BUCKET"
echo "Website URL: $WEBSITE_URL"

# Update frontend config with API URL
echo ""
echo "Updating frontend configuration..."
cat > frontend/config.js << EOF
// Configuration - Auto-generated by deploy.sh
// Environment: $ENV
// Generated: $(date)

const API_URL = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
    ? 'http://localhost:3000'
    : '$API_URL';
EOF

echo "Frontend config updated with API URL: $API_URL"

# Upload frontend to S3
echo ""
echo "Uploading frontend to S3..."
aws s3 sync frontend/ s3://$WEBSITE_BUCKET/ \
    --delete \
    --cache-control "max-age=31536000" \
    --exclude "*.html" \
    --region $REGION

# Upload HTML files with shorter cache
aws s3 sync frontend/ s3://$WEBSITE_BUCKET/ \
    --delete \
    --cache-control "max-age=0, no-cache, no-store, must-revalidate" \
    --exclude "*" \
    --include "*.html" \
    --region $REGION

echo "Frontend uploaded successfully!"

# Update MCP server config
echo ""
echo "Updating MCP server configuration..."
echo "PULSE_API_URL=$API_URL" > mcp-server/.env.example

# Instructions for DNS (manual step)
echo ""
echo "============================================"
echo "DEPLOYMENT COMPLETE!"
echo "============================================"
echo ""
echo "S3 Website URL: $WEBSITE_URL"
echo "API URL: $API_URL"
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Configure DNS for $DOMAIN:"
echo "   - Option A: Create CNAME record pointing to S3 website endpoint"
echo "   - Option B: Set up CloudFront distribution with custom domain"
echo ""
echo "2. For MCP Server (Braintrust integration):"
echo "   cd mcp-server && npm install"
echo "   export PULSE_API_URL=$API_URL"
echo ""
echo "3. To test locally:"
echo "   cd frontend && python -m http.server 8080"
echo "   Open http://localhost:8080"
echo ""
